- hosts: jenkins
  tasks:
    - name: update system
      become: yes
      apt:
        upgrade: dist
        update_cache: yes
      register: update_result
    - name: restart system
      become: yes
      shell: sleep 5 && shutdown -r now
      async: 1
      poll: 0
      when: update_result.changed
    - name: wait 10 seconds
      pause:
        seconds: 10
      when: update_result.changed
    - name: wait for system to restart
      wait_for:
        port: 22
        timeout: 180
      when: update_result.changed
    - name: install curl
      become: yes
      apt:
        name: curl
        state: present
    - name: install nvm
      shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
    - name: install node version 12
      shell: bash -c '. ~/.nvm/nvm.sh && nvm install lts/erbium'
    - name: install yarn
      shell: bash -c '. ~/.nvm/nvm.sh && npm install -g yarn'
    - name: install poetry
      shell: bash -c 'curl -sSL https://install.python-poetry.org | python3 -'
    - name: install software-properties-common
      become: yes
      apt:
        name: software-properties-common
        state: present
    - name: add ppa:deadsnakes/ppa
      become: yes
      apt_repository:
          repo: ppa:deadsnakes/ppa
          state: present
    - name: install Python version 3.8
      become: yes
      apt:
        name: python3.8-full
        state: present
    - name: install python3.8-dev
      become: yes
      apt:
        name: python3.8-dev
        state: present
    - name: install pip
      become: yes
      apt:
        name: python3-pip
        state: present
    - name: install solc version 0.5.15
      shell: curl -L -O https://github.com/ethereum/solidity/releases/download/v0.5.15/solc-static-linux && chmod +x solc-static-linux && sudo mv solc-static-linux /usr/local/bin/solc
    - name: install java version 17
      become: yes
      apt:
        name: openjdk-17-jdk
        state: present
    - name: download Jenkins
      get_url:
        url: https://get.jenkins.io/war-stable/2.387.2/jenkins.war
        dest: /home/ubuntu/jenkins.war
    - name: set priviliged ports down to 80 via sysctl
      become: yes
      sysctl:
        name: net.ipv4.ip_unprivileged_port_start
        value: 80
        sysctl_set: yes
        state: present
        reload: yes
